// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWv9nQiR1Zht3u8Zhg2uM_6SgVUUvmaqA',
    appId: '1:1067346595846:web:4ef8297918188b503e7387',
    messagingSenderId: '1067346595846',
    projectId: 'radio-crestin-aea7e',
    authDomain: 'radio-crestin-aea7e.firebaseapp.com',
    storageBucket: 'radio-crestin-aea7e.appspot.com',
    measurementId: 'G-MF5NVKRQ5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi3B0VC8ixYPOdG-of9CJb_m1ejGexYgs',
    appId: '1:1067346595846:android:151bbec6d16276113e7387',
    messagingSenderId: '1067346595846',
    projectId: 'radio-crestin-aea7e',
    storageBucket: 'radio-crestin-aea7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8an2f1oFqTL1__VN3egr71Eka4xULb_A',
    appId: '1:1067346595846:ios:f35180434dabf50f3e7387',
    messagingSenderId: '1067346595846',
    projectId: 'radio-crestin-aea7e',
    storageBucket: 'radio-crestin-aea7e.appspot.com',
    iosClientId: '1067346595846-vhsuuj67grmigu773o9dbdhv2s75vt9e.apps.googleusercontent.com',
    iosBundleId: 'com.radiocrestinsoftware.radioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8an2f1oFqTL1__VN3egr71Eka4xULb_A',
    appId: '1:1067346595846:ios:f35180434dabf50f3e7387',
    messagingSenderId: '1067346595846',
    projectId: 'radio-crestin-aea7e',
    storageBucket: 'radio-crestin-aea7e.appspot.com',
    iosClientId: '1067346595846-vhsuuj67grmigu773o9dbdhv2s75vt9e.apps.googleusercontent.com',
    iosBundleId: 'com.radiocrestinsoftware.radioApp',
  );
}
